Hw03
made-mlops-2022/ilya_verendeev_mlops pull request #3
Opened 2022-12-01 15:00 UTC by Z5-05

- [x] Поднимите airflow локально, используя docker compose (можно использовать из примера https://github.com/made-ml-in-prod-2021/airflow-examples/)

- [x] Реализуйте dag, который генерирует данные для обучения модели (генерируйте данные -- можете использовать как генератор синтетики из первой дз, так и что-то из датасетов sklearn). Вам важно проэмулировать ситуации постоянно поступающих данных (5 баллов)

- [x] записывайте данные в /data/raw/{{ ds }}/data.csv и /data/raw/{{ ds }}/target.csv
Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. В вашем пайплайне должно быть как минимум 4 стадии, но дайте волю своей фантазии =) (10 баллов)

- [x] Реализуйте dag, который использует модель ежедневно (5 баллов)

- [x] все даги реализованы только с помощью DockerOperator (пример https://github.com/made-ml-in-prod-2021/airflow-examples/blob/main/dags/11_docker.py). По технике, вы можете использовать такую же структуру как в примере, пакуя в разные докеры скрипты, можете использовать общий докер с вашим пакетом, но с разными точками входа для разных тасок. Прикольно, если вы покажете, что для разных тасок можно использовать разный набор зависимостей (10 баллов)

- [x] Традиционно, самооценка (1 балл)

Дополнительная часть:

- [x] Реализуйте сенсоры на то, что данные готовы для дагов тренировки и обучения (+3 доп балла)
Протестируйте ваши даги https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html (+5 доп баллов)
В docker compose так же настройте поднятие mlflow и запишите туда параметры обучения, метрики и артефакт (модель) (+5 доп баллов)
- [x] Вместо пути в airflow variables используйте API Mlflow Model Registry. Даг для инференса должен подхватывать последнюю продакшен модель (+5 доп баллов)
- [ ] Настройте alert в случае падения дага https://www.astronomer.io/guides/error-notifications-in-airflow (+3 доп балла)

2022-12-07 09:29 UTC, bulaevvi requested changes
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в исполненном без ошибок виде) и прикрепите их в описание пулл реквеста". У Вас нет скриншотов дагов в исполненном виде. См. пример скриншотов в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946
Без подтверждающих скриншотов баллы не будут начислены!

2022-12-07 10:27 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-07 21:50 UTC, Z5-05 commented
Общая картина ```airflow```
![image](https://user-images.githubusercontent.com/99659884/206303643-a4c4415a-4184-4478-a9c2-7bf468b9c015.png)
Таска ```generate```
![image](https://user-images.githubusercontent.com/99659884/206303721-4e7d339b-dcbb-41bb-ac31-182019d1cb85.png)
Таска ```train```
![image](https://user-images.githubusercontent.com/99659884/206303829-d662251c-a15b-4abb-991d-df98a8a80dbb.png)
Таска ```predict```
![image](https://user-images.githubusercontent.com/99659884/206303902-07fcda68-747f-49e7-a60e-6d5bfc6aa34d.png)
```MLFlow эксперименты```
![image](https://user-images.githubusercontent.com/99659884/206303993-f12c24f3-7fc0-423f-9f43-11056347bb78.png)
```MLFlow модели```
![image](https://user-images.githubusercontent.com/99659884/206304072-16900568-516a-44b8-aa08-3376812f03cb.png)
Вроде все заскринил :)

2022-12-08 04:35 UTC, bulaevvi approved these changes
Итого 41 балл. Делайте merge

2022-12-08 08:00 UTC, merged